name: Deploy Static Site & Infra

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            ${{ secrets.AWS_REGION }}

      # Build-time env for Next.js
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ——————————————————————
      # Terraform Init & Apply
      # ——————————————————————
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -var-file="terraform.tfvars" -auto-approve

      # ——————————————————————
      # Build & Export Next.js Static Site
      # ——————————————————————
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        run: |
          npm ci
          npm run build

      # ——————————————————————
      # Sync Exported Static Site to S3
      # ——————————————————————
      - name: Sync to S3
        run: |
          aws s3 sync ./out/ s3://$(terraform -chdir=infra output -raw bucket_name)/ --delete
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
